# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow integrates a collection of open source static analysis tools
# with GitHub code scanning. For documentation, or to provide feedback, visit
# https://github.com/microsoft/security-devops-action
name: OSSAR

on:
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]
  schedule:
    - cron: "35 7 * * 3"

permissions:
  contents: read

jobs:
  OSSAR-Scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # Run Microsoft Security DevOps
      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@4eaf69ee6aff7104270029dbfd8d3c0ba2853174 # v1.12.0
        id: msdo

        # Upload results to the Security tab
      - name: Upload results to Security tab
        uses: github/codeql-action/upload-sarif@662472033e742c64335064c49e2a2fb20f8e09a6 # v3.27.5
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
